---
galaxy_info:
  author: Clayton Coleman
  description: OpenShift Control Plane
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
- role: lib_openshift
- role: lib_utils
- role: openshift_facts
