- name: Docker config
  file:
    path: etc/docker
    state: directory

- name: docker国内镜像加速
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: restart docker
  service:
    name: docker
    state: restarted
