---

- name: Create some directory for doing work in
  file:
    path: "/opt/kubeOperator-kube-bin/1.13.5"
    state: "directory"
  register: temp

- debug:
    msg: "Create temp dir {{temp.path}}"

- name: Download bin kube file
  get_url:
    url: "http://{{local_hostname}}:{{repo_port}}/repository/k8s-basic-package/1.13.5/k8s.1-13-5.tar.gz"
    dest: "{{temp.path}}/k8s.1-13-5.tar.gz"

- name: Unarchive package
  unarchive:
    src: "{{temp.path}}/k8s.1-13-5.tar.gz"
    dest: "{{temp.path}}"
    copy: no

- name: Download manifests
  get_url:
    url: "http://{{local_hostname}}:{{repo_port}}/repository/k8s-basic-package/1.13.5/k8s.1-13-5-deploy.tar.gz"
    dest: "{{temp.path}}/k8s.1-13-5-deploy.tar.gz"

- name: Unarchive package
  unarchive:
    src: "{{temp.path}}/k8s.1-13-5-deploy.tar.gz"
    dest: "{{temp.path}}"
    copy: no