- name: 下载 ansible RPM
  get_url:
    url: "http://{{local_hostname}}:8082/repository/raw/rpms/ansible-2.4.2.0-2.el7.noarch.rpm"
    dest: /tmp/ansible-2.4.2.0-2.el7.noarch.rpm

- name: 安装 ansible
  shell: which ansible || rpm -i /tmp/ansible-2.4.2.0-2.el7.noarch.rpm

- name: 清理 tmp
  shell: rm -fr /tmp/ansible-2.4.2.0-2.el7.noarch.rpm

- name: 配置ansible
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg