apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meterings.metering.openshift.io
  annotations:
    catalog.app.coreos.com/description: An instance of Metering
    catalog.app.coreos.com/displayName: Metering
spec:
  group: metering.openshift.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: meterings
    singular: metering
    kind: Metering
    listKind: MeteringList
