DEBUG: false
DB_HOST: mysql
DB_USER: root
DB_PASSWORD: SuMk2lH20ocmvyu1p38m40
DB_NAME: kube-operator
REDIS_HOST: redis
ELASTICSEARCH_HOST: elasticsearch
ELASTICSEARCH_PORT: 9200
SECRET_KEY: "bl6HBTgAtQfKsaJTJb6tar6xgXyjGkLcfaLLw5rT33r4W0bpF2"
