{{ if .Values.notary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "harbor.notary-signer" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary-signer
spec:
  replicas: {{ .Values.notary.signer.replicas }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: notary-signer
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: notary-signer
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/notary/notary-cm.yaml") . | sha256sum }}
    spec:
      containers:
      - name: notary-signer
        image: {{ .Values.notary.signer.image.repository }}:{{ .Values.notary.signer.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
{{- if .Values.notary.signer.resources }}
        resources:
{{ toYaml .Values.notary.signer.resources | indent 10 }}
{{- end }}
        env:
        - name: MIGRATIONS_PATH
          value: migrations/signer/postgresql
        - name: DB_URL
          value: {{ template "harbor.database.notarySigner" . }}
        - name: NOTARY_SIGNER_DEFAULTALIAS
          value: defaultalias
        volumeMounts:
        - name: notary-config
          mountPath: /etc/notary
        {{- if .Values.notary.secretName }}
        - name: notary-cert
          mountPath: /etc/ssl/notary/cert/notary-signer-ca.crt
          subPath: ca
        - name: notary-cert
          mountPath: /etc/ssl/notary/cert/notary-signer.crt
          subPath: crt
        - name: notary-cert
          mountPath: /etc/ssl/notary/cert/notary-signer.key
          subPath: key
        {{- end }}
      volumes:
      - name: notary-config
        configMap:
          name: "{{ template "harbor.notary-server" . }}"
      {{- if .Values.notary.secretName }}
      - name: notary-cert
        secret:
          secretName: {{ .Values.notary.secretName }}
      {{- end }}
    {{- with .Values.notary.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.notary.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.notary.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
