---
galaxy_info:
  author: OpenShift
  description: docker garbage collection
  company: Red Hat, Inc
  license: ASL 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
- role: lib_openshift
- role: lib_utils
- role: openshift_facts
