---
### Common settings
openshift_logging_elasticsearch_image_pull_secret: "{{ openshift_logging_image_pull_secret }}"
openshift_logging_elasticsearch_namespace: openshift-logging

openshift_logging_elasticsearch_nodeselector: "{{ openshift_logging_es_nodeselector | default('') }}"
openshift_logging_elasticsearch_cpu_limit: null
openshift_logging_elasticsearch_cpu_request: "{{ openshift_logging_es_cpu_request | default('1000m') }}"
openshift_logging_elasticsearch_memory_limit: "{{ openshift_logging_es_memory_limit | default('16Gi') }}"
openshift_logging_elasticsearch_recover_after_time: "{{ openshift_logging_es_recover_after_time | default('5m') }}"

openshift_logging_elasticsearch_replica_count: 1

# ES deployment type
openshift_logging_elasticsearch_deployment_type: "data-master"

# ES deployment name
openshift_logging_elasticsearch_deployment_name: ""

# One of ['emptydir', 'pvc', 'hostmount']
openshift_logging_elasticsearch_storage_type: "emptydir"

# hostmount options
openshift_logging_elasticsearch_hostmount_path: ""

# pvc options
# the name of the PVC we will bind to -- create it if it does not exist
openshift_logging_elasticsearch_pvc_name: ""

# required if the PVC does not already exist
openshift_logging_elasticsearch_pvc_size: ""
openshift_logging_elasticsearch_pvc_dynamic: false
openshift_logging_elasticsearch_pvc_pv_selector: {}
openshift_logging_elasticsearch_pvc_storage_class_name: ""
openshift_logging_elasticsearch_pvc_access_modes: ['ReadWriteOnce']
openshift_logging_elasticsearch_storage_group: ['65534']

openshift_logging_es_pvc_prefix: "logging-es"

# config the es plugin to write kibana index based on the index mode
openshift_logging_elasticsearch_kibana_index_mode: 'unique'

openshift_logging_elasticsearch_proxy_cpu_request: "100m"
openshift_logging_elasticsearch_proxy_memory_limit: "64Mi"
openshift_logging_elasticsearch_prometheus_sa: "system:serviceaccount:{{openshift_prometheus_namespace | default('openshift-metrics')}}:prometheus"

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_logging_elasticsearch_ops_deployment: false

openshift_logging_elasticsearch_ops_allow_cluster_reader: false

# openshift_logging_es_config is a hash to be merged into the defaults for the elasticsearch.yaml
openshift_logging_es_config: {}


openshift_logging_master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
openshift_logging_master_public_url: "{{ 'https://' + openshift.common.public_hostname + ':' ~ openshift_master_api_port }}"
openshift_logging_es_host: logging-es
openshift_logging_es_port: 9200
openshift_logging_es_ca: /etc/fluent/keys/ca
openshift_logging_es_client_cert: /etc/fluent/keys/cert
openshift_logging_es_client_key: /etc/fluent/keys/key
