- name: 获取所有已经创建的POD信息
  command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
  register: pod_info

- import_tasks: nfs-client.yml
  when:
    - 'storage_nfs_enabled is defined '
    - 'storage_nfs_enabled '
    - '"nfs-provisioner" not in pod_info.stdout'

- import_tasks: vsphere-client.yml
  when:
    - 'storage_vsan_enabled is defined'
    - 'storage_vsan_enabled'

- import_tasks: cinder-client.yml
  when:
    - 'storage_cinder_enabled is defined'
    - 'storage_cinder_enabled'

- name: copy test-sc.yaml
  template:
    src: test/test-sc.yaml.j2
    dest: "/tmp/test-sc.yaml"

- name: verify storageclass availability
  shell: "kubectl -n default apply -f /tmp/test-sc.yaml"

- name: 轮询等待 storageclass验证结果
  shell: "{{ bin_dir }}/kubectl -n default get pod -o wide | grep {{ cluster_name }}-pod | awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Completed"
  delegate_to: "{{ groups['kube-master'][0] }}"
  retries: 10
  delay: 5

- name: delete test-sc.yaml
  shell: "kubectl -n default delete -f /tmp/test-sc.yaml"
