- import_tasks: nfs-client.yml
  when:
    - 'storage_nfs_enabled is defined '
    - 'storage_nfs_enabled '

- import_tasks: vsphere-client.yml
  when:
    - 'storage_vsan_enabled is defined'
    - 'storage_vsan_enabled'

- import_tasks: cinder-client.yml
  when:
    - 'storage_cinder_enabled is defined'
    - 'storage_cinder_enabled'

- import_tasks: rook-ceph.yml
  when:
    - 'storage_rook_ceph_enabled is defined'
    - 'storage_rook_ceph_enabled'
    - 'storage_rook_ceph_install'

- block:
    - name: copy test-sc.yaml
      template:
        src: test/test-sc.yaml.j2
        dest: "/tmp/test-sc.yaml"

    - name: verify storageclass availability
      shell: "kubectl -n default apply -f /tmp/test-sc.yaml"

    - name: 轮询等待 storageclass验证结果
      shell: "{{ bin_dir }}/kubectl -n default get pod -o wide | grep {{ cluster_name }}-pod | awk '{print $3}'"
      register: pod_status
      until: pod_status.stdout == "Completed"
      delegate_to: "{{ groups['kube-master'][0] }}"
      retries: 10
      delay: 10

    - name: delete test-sc.yaml
      shell: "kubectl -n default delete -f /tmp/test-sc.yaml"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true