- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind utilities are installed.
  package: name=rpcbind state=present

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"


- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length