apiVersion: v1
appVersion: v1.2.0
description: 'Loki: like Prometheus, but for logs.'
engine: gotpl
home: https://grafana.com/loki
icon: https://github.com/grafana/loki/raw/master/docs/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: loki
sources:
- https://github.com/grafana/loki
version: 0.22.0
