- name: 添加集群上游解析记录
  blockinfile:
    path: /opt/kubeOperator-api/dns/dns.conf
    block: "{{cluster_name}}.{{domain_suffix}} {\n
      forward . {{forward}}\n
  }\n"
    marker: "#{mark} {{cluster_name}}"
    state: present