apiVersion: v1
kind: Template
labels:
  template: manageiq-app-pv
metadata:
  name: manageiq-app-pv
  annotations:
    description: PV Template for MIQ Server
    tags: PVS, MIQ
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: miq-app
  spec:
    capacity:
      storage: "${PV_SIZE}"
    accessModes:
    - ReadWriteOnce
    nfs:
      path: "${BASE_PATH}/miq-app"
      server: "${NFS_HOST}"
    persistentVolumeReclaimPolicy: Retain
parameters:
- name: PV_SIZE
  displayName: PV Size for App
  required: true
  description: The size of the MIQ APP PV given in Gi
  value: 5Gi
- name: BASE_PATH
  displayName: Exports Directory Base Path
  required: true
  description: The parent directory of your NFS exports
  value: "/exports"
- name: NFS_HOST
  displayName: NFS Server Hostname
  required: true
  description: The hostname or IP address of the NFS server
