CLUSTER_DNS_SVC_IP: "{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') }}"
CLUSTER_DNS_DOMAIN: "cluster.local"
STORAGE_DIR: "/var/lib/docker"
# kubernetes 大版本号
kube_version_main: "{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}"
ingress_backend: "traefik"
