kind: List
apiVersion: v1
metadata:
  name: rhdm71-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Decision Manager 7.1
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm71-decisioncentral-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Decision Central 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.1 - Decision Central image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-decisioncentral-openshift:1.0
    - name: '1.1'
      annotations:
        description: Red Hat Decision Manager 7.1.1 - Decision Central image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-decisioncentral-openshift:1.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm71-controller-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Standalone Controller 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.1 - Standalone Controller image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-controller-openshift:1.0
    - name: '1.1'
      annotations:
        description: Red Hat Decision Manager 7.1.1 - Standalone Controller image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-controller-openshift:1.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm71-kieserver-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager KIE Server 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.1 - KIE Server image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-kieserver-openshift:1.0
    - name: '1.1'
      annotations:
        description: Red Hat Decision Manager 7.1.1 - KIE Server image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7/rhdm71-kieserver-openshift:1.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm71-decisioncentral-indexing-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager Decision Central Indexing 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.1 - Decision Central Indexing image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm71-decisioncentral-indexing-openshift:1.0
    - name: '1.1'
      annotations:
        description: Red Hat Decision Manager 7.1.1 - Decision Central Indexing image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm71-decisioncentral-indexing-openshift:1.1
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhdm71-optaweb-employee-rostering-openshift
    annotations:
      openshift.io/display-name: Red Hat Decision Manager KIE Server 7.1
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Decision Manager 7.1 - Business Optimizer OptaWeb Employee Rostering image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm71-optaweb-employee-rostering-openshift:1.0
    - name: '1.1'
      annotations:
        description: Red Hat Decision Manager 7.1.1 - Business Optimizer OptaWeb Employee Rostering image.
        iconClass: icon-jboss
        tags: rhdm
        supports: rhdm:7.1
        version: '1.1'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: registry.redhat.io/rhdm-7-tech-preview/rhdm71-optaweb-employee-rostering-openshift:1.1
