---

- name: Create some directory for doing work in
  file:
    path: "{{base_dir}}"
    state: "directory"
  register: temp

- debug:
    msg: "Create temp dir {{temp.path}}"

- name: Download bin kube file
  get_url:
    url: "http://{{local_hostname}}:8082/{{download_path}}"
    dest: "{{base_dir}}/{{file_name}}"

- name: Unarchive package
  unarchive:
    src: "{{base_dir}}/{{file_name}}"
    dest: "{{base_dir}}"
    copy: no

