---
- import_playbook: ../init/main.yml
  vars:
    l_init_fact_hosts: "oo_masters_to_config:oo_nfs_to_config"
    l_openshift_version_set_hosts: "oo_masters_to_config:!oo_first_master"
    l_sanity_check_hosts: "{{ groups['oo_masters_to_config'] | union(groups['oo_nfs_to_config']) }}"


- import_playbook: private/config.yml
