# 系统基础软件环境
- import_tasks: debian.yml
  when: 'ansible_distribution in ["Ubuntu","Debian"]'

- import_tasks: centos.yml
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]' 

# 公共系统参数设置
- import_tasks: common.yml

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"

- name: 分发证书工具 CFSSL
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 本地设置 bin 目录权限
  file: path={{ base_dir }}/bin state=directory mode=0755 recurse=yes
  connection: local
  run_once: true

- name: 添加 kubens
  copy:
    src: kubens
    dest: "{{bin_dir}}/kubens"
    mode: 0755

