---
- name: Generate new etcd CA
  hosts: oo_first_etcd
  tasks:
  - import_role:
      name: etcd
      tasks_from: ca.yml
    vars:
      etcd_peers: "{{ groups.oo_etcd_to_config | default([], true) }}"
      etcd_certificates_etcd_hosts: "{{ groups.oo_etcd_to_config | default([], true) }}"
    when:
    - etcd_ca_setup | default(True) | bool
