---
- name: Create etcd server certificates for etcd hosts
  hosts: oo_etcd_to_config
  any_errors_fatal: true
  tasks:
    - import_role:
        name: etcd
        tasks_from: server_certificates.yml
      vars:
        etcd_peers: "{{ groups.oo_etcd_to_config | default([], true) }}"
        etcd_certificates_etcd_hosts: "{{ groups.oo_etcd_to_config | default([], true) }}"
