- name: 开启firewalld 防火墙
  service:
    name: firewalld
    state: started
    enabled: true

- name: 打开防火墙UDP端口
  firewalld:
    port: "{{item}}/udp"
    permanent: true
    state: enabled
  with_items: "{{firewall_udp_ports}}"

- name: 打开防火墙TCP端口
  firewalld:
    port: "{{item}}/tcp"
    permanent: true
    state: enabled
  with_items: "{{firewall_tcp_ports}}"

- name: 打开防火墙 Node Port 端口
  firewalld:
    port: "30000-32767/tcp"
    permanent: true
    state: enabled
    
- name: 打开ssh 端口
  firewalld:
    port: "{{ansible_ssh_port}}/tcp"
    permanent: true
    state: enabled

- name: 打开postgresql 端口
  firewalld:
    port: "5432/tcp"
    permanent: true
    state: enabled
  when:
    - 'kubeapps_install is defined'
    - 'kubeapps_install'

- name: 打开istio-galley 端口
  firewalld:
    port: "9901/tcp"
    permanent: true
    state: enabled
  when:
    - 'kubeapps_install is defined'
    - 'kubeapps_install'

- name: 生效防火墙配置
  shell: "firewall-cmd --reload"

- name: 配置主机名
  hostname:
    name: "{{inventory_hostname}}"
