---
- import_playbook: ../init/main.yml

- name: Gather Cluster facts
  hosts: oo_all_hosts
  roles:
  - openshift_facts
  tasks:
  - openshift_facts: {}
    register: result
  - debug:
      var: result
