- name: get current docker storage
  shell: "docker info | grep 'Storage Driver' | awk -F: '{print $2}'"
  register: dockerStorage

- debug:
    msg: "{{ dockerStorage.stdout }}"

- name: config docker-storage-setup
  template:
    dest: "/etc/sysconfig/docker-storage-setup"
    src: "templates/docker-storage-setup.j2"
  when: dockerStorage.stdout != "devicemapper"

- name: remove config
  file:  
    path: /etc/sysconfig/docker-storage
    state: absent 
  when: dockerStorage.stdout != "devicemapper"

- name: execute docker-storage-setup
  shell: docker-storage-setup
  when: dockerStorage.stdout != "devicemapper"

- name: restart docker
  service:
    name: docker
    state: restarted
  when: dockerStorage.stdout != "devicemapper"
