---
- name: Alert user to variables needed
  hosts: localhost
  tasks:
  - name: Alert user to variables needed - clusterid
    debug:
      msg: "openshift_aws_clusterid={{ openshift_aws_clusterid | default('default') }}"

  - name: Alert user to variables needed - region
    debug:
      msg: "openshift_aws_region={{ openshift_aws_region | default('us-east-1') }}"

- name: Setup the master node group
  hosts: localhost
  tasks:
  - import_role:
      name: openshift_aws
      tasks_from: setup_master_group.yml

- name: run the init
  import_playbook: ../../../init/main.yml

- name: Run openshift-metrics playbook
  import_playbook: ../../../openshift-metrics/private/config.yml
  when: openshift_metrics_install_metrics | default(false) | bool
