---
galaxy_info:
  author: Troy Dawson
  description: Expand partition and filesystem to fill free space on disks.
  company: Red Hat, Inc.
  license: license (Apache)
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - all
  categories:
  - openshift
  - cloud
dependencies: []
