apiVersion: v1
appVersion: v0.4.0
description: Responsible for gathering logs and sending them to Loki
engine: gotpl
home: https://grafana.com/loki
icon: https://github.com/grafana/loki/raw/master/docs/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: promtail
sources:
- https://github.com/grafana/loki
version: 0.13.0
