kind: Pod
apiVersion: v1
metadata:
  name: master-api
  namespace: kube-system
  labels:
    openshift.io/control-plane: "true"
    openshift.io/component: api
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  restartPolicy: Always
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: api
    image: docker.io/openshift/origin:v3.11.0
    command: ["/bin/bash", "-c"]
    args:
    - |
      #!/bin/bash
      set -euo pipefail
      if [[ -f /etc/origin/master/master.env ]]; then
        set -o allexport
        source /etc/origin/master/master.env
      fi
      exec openshift start master api --config=/etc/origin/master/master-config.yaml --loglevel=${DEBUG_LOGLEVEL:-2}
    securityContext:
      privileged: true
    volumeMounts:
     - mountPath: /etc/origin/master/
       name: master-config
     - mountPath: /etc/origin/cloudprovider/
       name: master-cloud-provider
     - mountPath: /var/lib/origin/
       name: master-data
     - mountPath: /etc/pki
       name: master-pki
    livenessProbe:
      httpGet:
        scheme: HTTPS
        port: 8443
        path: healthz
      initialDelaySeconds: 45
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        scheme: HTTPS
        port: 8443
        path: healthz/ready
      initialDelaySeconds: 10
      timeoutSeconds: 10
  volumes:
  - name: master-config
    hostPath:
      path: /etc/origin/master/
  - name: master-cloud-provider
    hostPath:
      path: /etc/origin/cloudprovider
  - name: master-data
    hostPath:
      path: /var/lib/origin
  - name: master-pki
    hostPath:
      path: /etc/pki
