---
- name: modify controller args
  yedit:
    src: /etc/origin/master/master-config.yaml
    edits:
    - key: kubernetesMasterConfig.controllerArguments.cloud-config
      value:
      - "{{ openshift.common.config_base }}/cloudprovider/vsphere.conf"
    - key: kubernetesMasterConfig.controllerArguments.cloud-provider
      value:
      - vsphere
    - key: kubernetesMasterConfig.apiServerArguments.cloud-config
      value:
      - "{{ openshift.common.config_base }}/cloudprovider/vsphere.conf"
    - key: kubernetesMasterConfig.apiServerArguments.cloud-provider
      value:
      - vsphere
  notify: restart master
