apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv03
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: "/exports/miq-pv03"
    server: "<your-nfs-host-here>"
  persistentVolumeReclaimPolicy: Retain
