---
galaxy_info:
  author: Scott Dodson
  description: OpenShift Excluder
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
- role: openshift_facts
- role: lib_utils
