---
### General logging settings
openshift_logging_curator_image_pull_secret: "{{ openshift_logging_image_pull_secret }}"
openshift_logging_curator_master_url: "https://kubernetes.default.svc.cluster.local"

openshift_logging_curator_namespace: openshift-logging

### Common settings
openshift_logging_curator_nodeselector: ""
openshift_logging_curator_cpu_limit: null
openshift_logging_curator_cpu_request: 100m
openshift_logging_curator_memory_limit: 256Mi

openshift_logging_curator_es_host: "logging-es"
openshift_logging_curator_es_port: 9200

# This should not exceed 1, should check for this
openshift_logging_curator_replicas: 1

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_logging_curator_ops_deployment: false

openshift_logging_curator_default_days: 30
openshift_logging_curator_run_hour: 3
openshift_logging_curator_run_minute: 30
openshift_logging_curator_run_timezone: UTC
openshift_logging_curator_script_log_level: INFO
openshift_logging_curator_log_level: ERROR
openshift_logging_curator_timeout: 300

# following can be uncommented to provide values for configmaps -- take care when providing file contents as it may cause your cluster to not operate correctly
#curator_config_contents:
