- name: 安装 haproxy
  yum:
    name: haproxy
    state: present

- name: 配置 haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: 开机启用haproxy服务
  service:
    name: haproxy
    enabled: yes

- name: 停止haproxy服务
  service:
    name: haproxy
    state: stopped

- name: 开启haproxy服务
  service:
    name: haproxy
    state: started

- name: 替换 kubeconfig 的 apiserver 地址
  lineinfile:
    dest: /root/.kube/config
    regexp: "^    server"
    line: "    server: {{ NODE_KUBE_APISERVER }}"

- name: 替换 kubelet.kubeconfig 的 apiserver 地址
  lineinfile:
    dest: /etc/kubernetes/kubelet.kubeconfig
    regexp: "^    server"
    line: "    server: {{ NODE_KUBE_APISERVER }}"

- name: 替换 kube-proxy.kubeconfig 的 apiserver 地址
  lineinfile:
    dest: /etc/kubernetes/kube-proxy.kubeconfig
    regexp: "^    server"
    line: "    server: {{ NODE_KUBE_APISERVER }}"

- name: restart kube-node service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - kubelet
  - kube-proxy
