- name: 安装 daemon 相关依赖
  package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"

- name: 创建 dns 目录
  file:
    path: /etc/coredns
    state: directory

- name: 生成集群 dns 配置文件
  template:
    src: dns.conf.j2
    dest:  /etc/coredns/dns.conf

- name: 插入 hosts 记录
  lineinfile:
    path: "/etc/hosts"
    regexp: '{{ local_hostname }}'
    line: "{{local_hostname}}  {{dns_repository_hostname}}"

- name: 确认 DNS 服务状态
  shell: "docker rm -f dns >/dev/null 2>&1"
  ignore_errors: true

- name: 启动 Core DNS
  shell: "docker run -d \
          -v /etc/coredns/:/root \
          -p 53:53/tcp \
          -p 53:53/udp \
          --name dns \
          {{registry_prefix}}:{{registry_port}}/{{ dns_image }}:{{dns_version}} \
          --conf /root/dns.conf"
  ignore_errors: true

- name: 生成 chrony server 配置文件
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: 生效 chrony server 配置
  service:
    name: chronyd
    state: restarted

- block:
    - name: 主动同步时间
      shell: "ntpdate {{groups['kube-master'][0]}} | hwclock -w"
      when: "inventory_hostname != groups['kube-master'][0]"
  when: "DEPLOY_MODE == 'multiple-master'"

