- name: 授信 ssh 免密登录
  authorized_key:
    user: root
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    state: present
    exclusive: no


- name: 忽略 ssh 登陆 key 校验
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UseDNS.*'
    line: UseDNS no
  notify:
    - restart sshd

- name: 推送 ssh 密钥对至 deploy节点
  copy: src=~/.ssh/{{ item }} dest=~/.ssh/{{ item }} mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true