- name: 下载helm客户端
  copy: src={{ base_dir }}/bin/helm dest={{ bin_dir }}/helm mode=0755

- name: 准备rbac配置
  template: src=helm-rbac.yaml.j2 dest=./helm-rbac.yaml

- name: 在k8s上创建rbac
  shell: "{{ bin_dir }}/kubectl apply -f ./helm-rbac.yaml"
  ignore_errors: true

- name: 安装tiller
  shell: "{{ bin_dir }}/helm init \
        --service-account {{ tiller_sa }} \
        --tiller-namespace {{ helm_namespace }} \
        --tiller-image {{registry_prefix}}/{{ tiller_image }}:{{tiller_version}}"
  ignore_errors: true

- name: 配置helm tls环境变量
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: "helm tls environment"
    line: "export HELM_TLS_ENABLE=false"

- name: 添加 helm 命令自动补全
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'helm completion'
    line: 'source <(helm completion bash)'

