---
- name: Create a directory to hold the certificates
  file: path="{{ nuage_plugin_rest_client_crt_dir }}" state=directory
  delegate_to: "{{ nuage_ca_master }}"

- name: Create the key
  command: >
    openssl genrsa -out "{{ nuage_ca_master_plugin_key }}" 4096
  delegate_to: "{{ nuage_ca_master }}"

- name: Create the req file
  command: >
    openssl req -key "{{ nuage_ca_master_plugin_key }}" -new -out "{{ nuage_plugin_rest_client_crt_dir }}/restClient.req" -subj "/CN=nuage-client"
  delegate_to: "{{ nuage_ca_master }}"

- name: Generate the crt file
  command: >
    openssl x509 -req -in "{{ nuage_plugin_rest_client_crt_dir }}/restClient.req" -CA "{{ nuage_ca_crt }}" -CAkey "{{ nuage_ca_key }}" -CAserial "{{ nuage_ca_serial }}"  -out "{{ nuage_ca_master_plugin_crt }}" -extensions clientauth -extfile "{{ nuage_ca_dir }}"/openssl.cnf -days {{ nuage_mon_cert_validity_period }}
  delegate_to: "{{ nuage_ca_master }}"

- name: Remove the req file
  file: path="{{ nuage_plugin_rest_client_crt_dir }}/restClient.req" state=absent
  delegate_to: "{{ nuage_ca_master }}"

- name: Copy nuage CA crt
  shell: cp "{{ nuage_ca_crt }}" "{{ nuage_plugin_rest_client_crt_dir }}"
  delegate_to: "{{ nuage_ca_master }}"

- name: Archive the certificate dir
  shell: "cd {{ nuage_plugin_rest_client_crt_dir }} && tar -czvf /tmp/{{ ansible_nodename }}.tgz *"
  delegate_to: "{{ nuage_ca_master }}"

- name: Create a temp directory for the certificates
  local_action: command mktemp -d "/tmp/openshift-{{ ansible_nodename }}-XXXXXXX"
  register: mktemp

- name: Download the certificates
  fetch: src="/tmp/{{ ansible_nodename }}.tgz" dest="{{ mktemp.stdout }}/{{ ansible_nodename }}.tgz" flat=yes
  delegate_to: "{{ nuage_ca_master }}"

- name: Extract the certificates
  unarchive: src="{{ mktemp.stdout }}/{{ ansible_nodename }}.tgz" dest={{ nuage_plugin_crt_dir }}

- name: Delete the certificates after copy
  file: path="{{ nuage_plugin_rest_client_crt_dir }}" state=absent
  delegate_to: "{{ nuage_ca_master }}"

- name: Delete the temp directory
  file: path="{{ mktemp.stdout }}" state=absent
  delegate_to: "{{ nuage_ca_master }}"
