- name: 获取 helm 版本信息
  shell: "helm version -c --short | awk '{print substr($2,1,7)}'"
  register: helm_ver

- block:
    - name: Download helm client
      copy: src={{ base_dir }}/bin/helm dest={{ bin_dir }}/helm mode=0755

    - name: Upgrade tiller
      shell: "{{ bin_dir }}/helm init --upgrade \
              --service-account {{ tiller_sa }} \
              --tiller-namespace {{ helm_namespace }} \
              --tiller-image {{registry_prefix}}:{{registry_port}}/{{ tiller_image }}:{{tiller_version}} \
              --skip-refresh"
      ignore_errors: true

    - name: wait tiller complete
      shell: "{{ bin_dir }}/kubectl get pod -n kube-system | grep 'tiller' | awk '{print $3}'"
      register: tiller_status
      until: tiller_status.stdout == 'Running'
      retries: 20
      delay: 5
  when:
    - 'helm_version is defined'
    - 'helm_ver.stdout < helm_version'
