---
- name: reload systemd
  command: systemctl --system daemon-reload

- name: restart netmaster
  service:
    name: netmaster
    state: restarted

- name: restart netplugin
  service:
    name: netplugin
    state: restarted

- name: Save iptables rules
  command: service iptables save
