packages:
  - wget
  - net-tools
  - bind-utils
  - firewalld
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - glibc-common
  - bind-license
  - python-passlib
  - chrony
  - python-docker-py

firewall_tcp_ports:
  - 4789
  - 8443
  - 80
  - 443
  - 53
  - 10250
  - 2049
  - 2379
  - 2380
  - 4001
  - 4789
  - 9000
  - 1936
  - 9200
  - 9300
  - 123
firewall_udp_ports:
  - 53
  - 123
