packages:
  - wget
  - net-tools
  - bind-utils
  - firewalld
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - glibc-common
  - bind-license
  - python-passlib
  - chrony
  - python-docker-py
  - ntpdate
  - jq

firewall_tcp_ports:
  - 53
  - 80
  - 123
  - 179
  - 443
  - 2379
  - 2380
  - 6443
  - 6784
  - 8080
  - 8443
  - 8472
  - 8580
  - 10250
  - 10251
  - 10252
  - 10253
  - 10254
  - 10255
  - 1936
  - 2049
  - 4001
  - 4789
  - 9000
  - 9100
  - 9200
  - 9300

firewall_udp_ports:
  - 53
  - 123
  - 8472
