---

- name: Create some directory for doing work in
  file:
    path: "/opt/kubeOperator-kube-bin/1.15.0"
    state: "directory"
  register: temp

- debug:
    msg: "Create temp dir {{temp.path}}"

- name: Download bin kube file
  get_url:
    url: "http://{{local_hostname}}:8082/repository/raw/1.15.0/k8s.1-15-0.tar.gz"
    dest: "{{temp.path}}/k8s.1-15-0.tar.gz"

- name: Unarchive package
  unarchive:
    src: "{{temp.path}}/k8s.1-15-0.tar.gz"
    dest: "{{temp.path}}"
    copy: no

