basePath: /api/v1
definitions:
  dto.Cluster:
    properties:
      architectures:
        type: string
      createdAt:
        type: string
      name:
        type: string
      nodeSize:
        type: integer
      provider:
        type: string
      source:
        type: string
      spec:
        $ref: '#/definitions/model.ClusterSpec'
        type: object
      status:
        type: string
      updatedAt:
        type: string
    type: object
  dto.ClusterCreate:
    properties:
      architectures:
        type: string
      calicoIpv4PoolIpip:
        type: string
      containerdStorageDIr:
        type: string
      dockerStorageDIr:
        type: string
      dockerSubnet:
        type: string
      flannelBackend:
        type: string
      ingressControllerType:
        type: string
      kubeMaxPods:
        type: integer
      kubePodSubnet:
        type: string
      kubeProxyMode:
        type: string
      kubeServiceSubnet:
        type: string
      kubernetesAudit:
        type: string
      name:
        type: string
      networkType:
        type: string
      nodes:
        items:
          $ref: '#/definitions/dto.NodeCreate'
        type: array
      plan:
        type: string
      projectName:
        type: string
      provider:
        type: string
      runtimeType:
        type: string
      version:
        type: string
      workerAmount:
        type: integer
    required:
    - name
    - version
    type: object
  dto.Host:
    properties:
      _:
        type: string
      clusterId:
        type: string
      clusterName:
        type: string
      cpuCore:
        type: integer
      createdAt:
        type: string
      credentialId:
        type: string
      gpuInfo:
        type: string
      gpuNum:
        type: integer
      ip:
        type: string
      memory:
        type: integer
      message:
        type: string
      name:
        type: string
      os:
        type: string
      osVersion:
        type: string
      port:
        type: integer
      status:
        type: string
      updatedAt:
        type: string
      volumes:
        items:
          $ref: '#/definitions/model.Volume'
        type: array
      zoneId:
        type: string
      zoneName:
        type: string
    type: object
  dto.HostCreate:
    properties:
      credentialId:
        type: string
      ip:
        type: string
      name:
        type: string
      port:
        type: integer
    required:
    - credentialId
    - ip
    - name
    - port
    type: object
  dto.NodeCreate:
    properties:
      hostName:
        type: string
      role:
        type: string
    type: object
  model.ClusterSpec:
    properties:
      _:
        type: string
      architectures:
        type: string
      calicoIpv4PoolIpip:
        type: string
      containerdStorageDir:
        type: string
      createdAt:
        type: string
      docker_subnet:
        type: string
      dockerStorageDir:
        type: string
      flannelBackend:
        type: string
      ingressControllerType:
        type: string
      kubeApiServerPort:
        type: integer
      kubeMaxPods:
        type: integer
      kubePodSubnet:
        type: string
      kubeProxyMode:
        type: string
      kubeRouter:
        type: string
      kubeServiceSubnet:
        type: string
      kubernetesAudit:
        type: string
      lbKubeApiserverIp:
        type: string
      networkType:
        type: string
      provider:
        type: string
      runtimeType:
        type: string
      updatedAt:
        type: string
      version:
        type: string
      workerAmount:
        type: integer
    type: object
  model.Volume:
    properties:
      createdAt:
        type: string
      hostId:
        type: string
      id:
        type: string
      name:
        type: string
      size:
        type: string
      updatedAt:
        type: string
    type: object
  page.Page:
    properties:
      items:
        type: object
      total:
        type: integer
    type: object
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
paths:
  /clusters/:
    get:
      consumes:
      - application/json
      description: Show a cluster
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Cluster'
      security:
      - ApiKeyAuth: []
      summary: Show a cluster
      tags:
      - clusters
    post:
      consumes:
      - application/json
      description: Create a cluster
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ClusterCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Cluster'
      security:
      - ApiKeyAuth: []
      summary: Create a cluster
      tags:
      - clusters
  /clusters/{name}/:
    delete:
      consumes:
      - application/json
      description: delete a cluster by name
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      summary: Delete a cluster
      tags:
      - clusters
  /hosts/:
    get:
      consumes:
      - application/json
      description: Show hosts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/page.Page'
      security:
      - ApiKeyAuth: []
      summary: Show all hosts
      tags:
      - hosts
    post:
      consumes:
      - application/json
      description: create a host
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.HostCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Host'
      security:
      - ApiKeyAuth: []
      summary: Create a host
      tags:
      - hosts
  /hosts/{name}/:
    delete:
      consumes:
      - application/json
      description: delete a host by name
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      summary: Delete a host
      tags:
      - hosts
    get:
      consumes:
      - application/json
      description: show a host by name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Host'
      security:
      - ApiKeyAuth: []
      summary: Show a host
      tags:
      - hosts
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
