basePath: /api/v1
definitions:
  serializer.BatchClusterRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
      operation:
        type: string
    required:
    - items
    - operation
    type: object
  serializer.BatchClusterResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
    type: object
  serializer.BatchCredentialRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Credential'
        type: array
      operation:
        type: string
    required:
    - operation
    type: object
  serializer.BatchCredentialResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Credential'
        type: array
    type: object
  serializer.BatchHostRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Host'
        type: array
      operation:
        type: string
    required:
    - operation
    type: object
  serializer.BatchHostResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Host'
        type: array
    type: object
  serializer.Cluster:
    properties:
      name:
        type: string
      spec:
        $ref: '#/definitions/serializer.Spec'
        type: object
    type: object
  serializer.CreateClusterRequest:
    properties:
      name:
        type: string
      version:
        type: string
    required:
    - name
    - version
    type: object
  serializer.CreateCredentialRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  serializer.CreateHostRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  serializer.Credential:
    properties:
      name:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  serializer.GetClusterResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Cluster'
        type: object
    type: object
  serializer.GetCredentialResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Credential'
        type: object
    type: object
  serializer.GetHostResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Host'
        type: object
    type: object
  serializer.Host:
    properties:
      cluster_id:
        type: string
      cpu_core:
        type: integer
      cpu_num:
        type: integer
      credential_id:
        type: string
      gpu_info:
        type: string
      id:
        type: string
      ip:
        type: string
      memory:
        type: string
      name:
        type: string
      node_id:
        type: string
      os:
        type: string
      os_version:
        type: string
      port:
        type: integer
      status:
        type: string
    type: object
  serializer.ListClusterResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
      total:
        type: integer
    type: object
  serializer.ListCredentialResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Credential'
        type: array
      total:
        type: integer
    type: object
  serializer.Spec:
    properties:
      version:
        type: string
    type: object
  serializer.UpdateClusterRequest:
    properties:
      item:
        $ref: '#/definitions/serializer.Cluster'
        type: object
    required:
    - item
    type: object
  serializer.UpdateCredentialRequest:
    properties:
      item:
        $ref: '#/definitions/serializer.Credential'
        type: object
    required:
    - item
    type: object
  serializer.UpdateHostRequest:
    properties:
      item:
        $ref: '#/definitions/serializer.Host'
        type: object
    required:
    - item
    type: object
host: localhost:8080
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
paths:
  /clusters/:
    get:
      consumes:
      - application/json
      description: List clusters
      parameters:
      - description: page num
        in: query
        name: pageNum
        type: string
      - description: page size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListClusterResponse'
      summary: Cluster
      tags:
      - Cluster
    post:
      consumes:
      - application/json
      description: Create a Cluster
      parameters:
      - description: cluster
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateClusterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/serializer.Cluster'
      summary: Cluster
      tags:
      - Cluster
  /clusters/{cluster_name}:
    delete:
      consumes:
      - application/json
      description: Delete a Cluster
      parameters:
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Cluster
      tags:
      - Cluster
    get:
      consumes:
      - application/json
      description: Get Cluster
      parameters:
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.GetClusterResponse'
      summary: Cluster
      tags:
      - Cluster
    patch:
      consumes:
      - application/json
      description: Update a Cluster
      parameters:
      - description: cluster
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateClusterRequest'
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Cluster'
      summary: Cluster
      tags:
      - Cluster
  /clusters/batch/:
    post:
      consumes:
      - application/json
      description: Batch Clusters
      parameters:
      - description: Batch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.BatchClusterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.BatchClusterResponse'
      summary: Cluster
      tags:
      - Cluster
  /credentials/:
    get:
      consumes:
      - application/json
      description: List credentials
      parameters:
      - description: page num
        in: query
        name: pageNum
        type: string
      - description: page size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListCredentialResponse'
      summary: Credential
      tags:
      - Credential
    post:
      consumes:
      - application/json
      description: Create a Credential
      parameters:
      - description: credential
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateCredentialRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/serializer.Credential'
      summary: Credential
      tags:
      - Credential
  /credentials/{credential_name}:
    delete:
      consumes:
      - application/json
      description: Delete a Credential
      parameters:
      - description: credential name
        in: path
        name: credential_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Credential
      tags:
      - Credential
    get:
      consumes:
      - application/json
      description: Get Credential
      parameters:
      - description: credential name
        in: path
        name: credential_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.GetCredentialResponse'
      summary: Credential
      tags:
      - Credential
    patch:
      consumes:
      - application/json
      description: Update a Credential
      parameters:
      - description: credential
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateCredentialRequest'
      - description: credential name
        in: path
        name: credential_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Credential'
      summary: Credential
      tags:
      - Credential
  /credentials/batch/:
    post:
      consumes:
      - application/json
      description: Batch Credentials
      parameters:
      - description: Batch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.BatchCredentialRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.BatchCredentialResponse'
      summary: Credential
      tags:
      - Credential
  /host/:
    post:
      consumes:
      - application/json
      description: Create a Host
      parameters:
      - description: host
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateHostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/serializer.Host'
      summary: Host
      tags:
      - Host
  /host/{host_name}:
    delete:
      consumes:
      - application/json
      description: Delete a Host
      parameters:
      - description: host name
        in: path
        name: host_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Host
      tags:
      - Host
    get:
      consumes:
      - application/json
      description: Get Host
      parameters:
      - description: host name
        in: path
        name: host_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.GetHostResponse'
      summary: Host
      tags:
      - Host
    patch:
      consumes:
      - application/json
      description: Update a Host
      parameters:
      - description: host
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateHostRequest'
      - description: host_name
        in: path
        name: host_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Host'
      summary: Host
      tags:
      - Host
  /host/batch/:
    post:
      consumes:
      - application/json
      description: Batch Host
      parameters:
      - description: Batch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.BatchHostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.BatchHostResponse'
      summary: Host
      tags:
      - Host
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
