---
### Common settings
openshift_logging_kibana_master_url: "https://kubernetes.default.svc.cluster.local"
openshift_logging_kibana_master_public_url: "https://kubernetes.default.svc.cluster.local"
openshift_logging_kibana_image_pull_secret: "{{ openshift_logging_image_pull_secret }}"
openshift_logging_kibana_namespace: openshift-logging

openshift_logging_kibana_nodeselector: ""
openshift_logging_kibana_cpu_limit: null
openshift_logging_kibana_cpu_request: 100m
openshift_logging_kibana_memory_limit: 736Mi

openshift_logging_kibana_hostname: "{{ 'kibana.' ~ openshift_master_default_subdomain }}"

openshift_logging_kibana_es_host: "logging-es"
openshift_logging_kibana_es_port: 9200

openshift_logging_kibana_replicas: 1
openshift_logging_kibana_edge_term_policy: Redirect

# map of env. var to add to the kibana deploymentconfig
openshift_logging_kibana_env_vars: {}

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_logging_kibana_ops_deployment: false

# Proxy settings
openshift_logging_kibana_proxy_debug: false
openshift_logging_kibana_proxy_cpu_limit: null
openshift_logging_kibana_proxy_cpu_request: 100m
openshift_logging_kibana_proxy_memory_limit: 256Mi

#The absolute path on the control node to the cert file to use
#for the public facing kibana certs
openshift_logging_kibana_cert: ""

#The absolute path on the control node to the key file to use
#for the public facing kibana certs
openshift_logging_kibana_key: ""

#The absolute path on the control node to the CA file to use
#for the public facing kibana certs
openshift_logging_kibana_ca: ""

# Value in OauthClient object definition that overwrites master-config
# 1 week = 168 hours = 604800 seconds
openshift_logging_kibana_session_timeout_seconds: 604800
