- name: prepare master cinder.conf
  template: src=cinder/cinder.conf.j2 dest=/usr/local/bin/cinder.conf

- name: prepare node cinder.conf
  template: src=cinder/cinder.conf.j2 dest=/usr/local/bin/cinder.conf
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-node'] }}"

- name: modify apiserver and controller-manager services on master node
  lineinfile:
    path: "{{ item.key }}"
    insertbefore: "--v=2"
    line: "{{ item.value }}"
  with_items:
    - { key: '/etc/systemd/system/kube-apiserver.service', value: '  --cloud-provider=openstack \'}
    - { key: '/etc/systemd/system/kube-controller-manager.service', value: '  --cloud-provider=openstack \'}
    - { key: '/etc/systemd/system/kube-apiserver.service', value: '  --cloud-config=/usr/local/bin/cinder.conf \'}
    - { key: '/etc/systemd/system/kube-controller-manager.service', value: '  --cloud-config=/usr/local/bin/cinder.conf \'}

- name: modify kubelet services on worker node
  lineinfile:
    path: "/etc/systemd/system/kubelet.service"
    insertbefore: "--v=2"
    line: '  --cloud-provider=openstack \'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-node'] }}"
  run_once: true

- name: modify kubelet services on worker node
  lineinfile:
    path: "/etc/systemd/system/kubelet.service"
    insertbefore: "--v=2"
    line: '  --cloud-config=/usr/local/bin/cinder.conf \'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-node'] }}"
  run_once: true

- name: restart kubelet service
  shell: "systemctl daemon-reload && systemctl restart kubelet"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-node'] }}"
  run_once: true

- name: restart apiserver and controller-manager service
  shell: "systemctl daemon-reload && systemctl restart kube-controller-manager && \
    systemctl restart kube-apiserver"

- block:
  - name: prepare cinder default storageclass file
    template:
      src: cinder/default-sc.yaml.j2
      dest: "/tmp/default-sc.yaml"

  - name: create cinder default storageclass
    shell: "{{ bin_dir }}/kubectl apply -f /tmp/default-sc.yaml"

  - name: 设置default storageClass
    shell: "{{ bin_dir }}/kubectl patch storageclass '{{ storageClassName }}' -p '{{default_label}}'"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true
