---
galaxy_info:
  author: Dan Osborne
  description: Calico networking
  company: Tigera, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
dependencies:
- role: openshift_facts
