---
# Must not be blank if you're using vsphere
openshift_cloudprovider_vsphere_datastore: ''

openshift_storageclass_defaults:
  aws:
    provisioner: aws-ebs
    name: gp2
    parameters:
      type: gp2
      kmsKeyId: ''
      encrypted: 'false'

  azure:
    provisioner: azure-disk
    name: azure-standard
    parameters:
      storageaccounttype: 'Standard_LRS'
      kind: 'Shared'

  gce:
    name: standard
    provisioner: gce-pd
    parameters:
      type: pd-standard

  openstack:
    name: standard
    provisioner: cinder
    parameters:
      fstype: xfs

  vsphere:
    provisioner: vsphere-volume
    name: vsphere-standard
    parameters:
      datastore: "{{ openshift_cloudprovider_vsphere_datastore }}"

openshift_storageclass_default: "true"
openshift_storageclass_name: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['name'] }}"
openshift_storageclass_provisioner: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['provisioner'] }}"
openshift_storageclass_parameters: "{{ openshift_storageclass_defaults[openshift_cloudprovider_kind]['parameters'] }}"
openshift_storageclass_mount_options: []
