- name: Backup original repos
  ignore_errors: yes
  shell: mkdir -p /etc/yum.repos.d/backup && /bin/mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup

- name: Create proxy repo 
  template:
    src: templates/fit2openshift.repo.j2
    dest: /etc/yum.repos.d/fit2openshift.repo

- name: Create pip conf dir
  file:
    path: ~/.pip
    state: directory

- name: Create pip repo
  template:
    src: templates/pip.conf.j2
    dest: ~/.pip/pip.conf