---
- import_playbook: ../init/main.yml
  vars:
    l_init_fact_hosts: "oo_masters_to_config"
    l_openshift_version_determine_hosts: "all:!all"
    l_openshift_version_set_hosts: "all:!all"
    skip_sanity_checks: True

- import_playbook: private/openshift_node_group.yml
