---
- name: Check that origin image is present
  command: "{{ openshift_container_cli }} images -q {{ osm_image }}"
  register: control_plane_image

# This task runs async to save time while the master is being configured
- name: Pre-pull Origin image (docker)
  command: "{{ openshift_container_cli }} pull {{ osm_image }}"
  environment:
    NO_PROXY: "{{ openshift.common.no_proxy | default('') }}"
  when: control_plane_image.stdout_lines == []
  # 10 minutes to pull the image
  async: 600
  poll: 0
  register: image_prepull
