---
- name: Alert user to variables needed
  hosts: localhost
  tasks:
  - name: Alert user to variables needed - clusterid
    debug:
      msg: "openshift_aws_clusterid={{ openshift_aws_clusterid | default('default') }}"

  - name: Alert user to variables needed - region
    debug:
      msg: "openshift_aws_region={{ openshift_aws_region | default('us-east-1') }}"

- import_playbook: provision_s3.yml

- import_playbook: provision_elb.yml

- name: Create the master instances
  hosts: localhost
  tasks:
  - name: provision instances
    import_role:
      name: openshift_aws
      tasks_from: provision_masters.yml

- import_playbook: provision_dns.yml
