---

# 修改安装rpm源
- name: replace repos.
  hosts: OSEv3
  roles:
  - replace_repos

# 安装基础rmp
- name: ensure nodes packages.
  hosts: nodes
  vars:
   packages:
      - java-1.8.0-openjdk-headless
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - glibc-common
      - bind-license
  serial: 1
  gather_facts: no
  roles:
  - check_packages_nodes

# 校验安装环境
- name: Validate environment
  gather_facts: no
  hosts: OSEv3
  tasks:
    - import_role:
         name: check_networking
#    - import_role:
#        name: check_disks
#    - import_role:
#        name: check_os
#    - import_role:
#        name: check_connectivity
#    - import_role:
#        name: check_sizing
#      when: inventory_hostname in groups['nodes']
#    - import_role:
#        name: check_dns
#    - import_role:
#        name: check_selinux
#    - import_role:
#        name: check_storage
#      when: inventory_hostname in groups['nodes']

# 初始化 firewall
- name: Initialize firewall check
  hosts: nodes
  vars:
    firewall_ports:
      - 4789
      - 8443
      - 80
      - 443
      - 53
      - 10250
      - 2049
      - 2379
      - 2380
      - 4001
      - 4789
      - 9000
      - 1936
      - 9200
      - 9300
  gather_facts: no
  roles:
  - check_firewall_initialize

- name: Cleanup validation trash
  hosts: OSEv3
  gather_facts: yes
  roles:
  - check_cleanup

