---
- import_playbook: ../init/main.yml
  vars:
    l_openshift_version_set_hosts: "all:!all"
    l_init_fact_hosts: "oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config"
    l_sanity_check_hosts: "{{ groups['oo_etcd_to_config'] | union(groups['oo_masters_to_config']) }}"

- import_playbook: private/ca.yml

- import_playbook: private/certificates.yml
